version: '3'
services:
  mysql:
    image: mariadb
#путь к хост-компьютеру монтируется в путь /data/mysqlк контейнеру /var/lib/mysql
#это позволяет хранить все наши файлы БД на хост-компьютере, а не в контейнере.
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    restart: always
    
  wordpress:
    image: wordpress:php7.3-fpm-alpine
#путь к хост-компьютеру монтируется в путь /data/html к контейнеру /var/www/html
    volumes:
      - ./data/html:/var/www/html
#служба WordPress зависит от службы mysql . Это означает, что службы запускаются и останавливаются в порядке зависимости.
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_TABLE_PREFIX: wp_
      
#позволяет службе WordPress взаимодействовать со службой mysql .
    links:
      - mysql
    restart: always
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./data/html:/var/www/html
#порт хост-компьютера 8080 сопоставляется с портом 80 контейнера
    ports:
      - 8080:80
    links:
      - wordpress